---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: cerium
# description will be included in the image's metadata
description: My solution to fill in the gap the deprecation ChromiumOS will cause.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/kinoite-main
image-version: 43

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    install:
      packages:
        - plasma-oxygen
    remove:
      packages:
        - firefox
        - firefox-langpacks
      
  - type: script
    scripts:
      #- gnome_config.sh
      - flatpak_config.sh
      
  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install:
          - org.mozilla.firefox
          - org.gnome.Loupe
      - scope: user

  - type: signing
